-- V15: Create HCC Suspecting Module tables
-- All tables prefixed with hcc_ as per isolation requirements
-- Uses GENERATED BY DEFAULT AS IDENTITY for H2/PostgreSQL compatibility

-- Main rule definition table
CREATE TABLE hcc_suspect_rule (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    hcc_category VARCHAR(50) NOT NULL,
    condition_name VARCHAR(255) NOT NULL,
    cms_enabled BOOLEAN DEFAULT TRUE,
    hhs_enabled BOOLEAN DEFAULT TRUE,
    esrd_enabled BOOLEAN DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    model_year VARCHAR(20),
    lookback_years INT DEFAULT 2,
    version INT DEFAULT 1,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_hcc_rule_status ON hcc_suspect_rule(status);
CREATE INDEX idx_hcc_rule_category ON hcc_suspect_rule(hcc_category);

-- Stratification tier (HS/MS criteria per rule)
CREATE TABLE hcc_stratification_tier (
    id BIGSERIAL PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    tier_type VARCHAR(30) NOT NULL,
    minimum_branches_required INT DEFAULT 1,
    criteria_json TEXT,
    supporting_facts_json TEXT,
    CONSTRAINT fk_tier_rule FOREIGN KEY (rule_id) REFERENCES hcc_suspect_rule(id) ON DELETE CASCADE
);

CREATE INDEX idx_tier_rule ON hcc_stratification_tier(rule_id);

-- Suppression configuration per model type (CMS/HHS/ESRD)
CREATE TABLE hcc_suppression_config (
    id BIGSERIAL PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    model_type VARCHAR(10) NOT NULL,
    target_hcc VARCHAR(100) NOT NULL,
    suppression_states TEXT,
    resurfacing_enabled BOOLEAN DEFAULT TRUE,
    resurfacing_requires_different_concept BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_suppression_rule FOREIGN KEY (rule_id) REFERENCES hcc_suspect_rule(id) ON DELETE CASCADE
);

CREATE INDEX idx_suppression_rule ON hcc_suppression_config(rule_id);

-- Client-specific overrides of canonical rules
CREATE TABLE hcc_client_config (
    id BIGSERIAL PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    client_id VARCHAR(100) NOT NULL,
    lookback_years_override INT,
    disabled_branch_ids TEXT,
    threshold_overrides_json TEXT,
    cms_enabled BOOLEAN,
    hhs_enabled BOOLEAN,
    esrd_enabled BOOLEAN,
    CONSTRAINT fk_client_rule FOREIGN KEY (rule_id) REFERENCES hcc_suspect_rule(id) ON DELETE CASCADE
);

CREATE INDEX idx_client_rule ON hcc_client_config(rule_id);
CREATE INDEX idx_client_id ON hcc_client_config(client_id);

-- Per-patient rejection state for resurfacing logic
CREATE TABLE hcc_rule_rejection_state (
    id BIGSERIAL PRIMARY KEY,
    patient_id VARCHAR(100) NOT NULL,
    rule_id BIGINT NOT NULL,
    model_type VARCHAR(10) NOT NULL,
    rejected_at DATE NOT NULL,
    last_triggering_concept_alias VARCHAR(255),
    CONSTRAINT fk_rejection_rule FOREIGN KEY (rule_id) REFERENCES hcc_suspect_rule(id) ON DELETE CASCADE
);

CREATE INDEX idx_rejection_patient ON hcc_rule_rejection_state(patient_id);
CREATE INDEX idx_rejection_rule ON hcc_rule_rejection_state(rule_id);
CREATE UNIQUE INDEX idx_rejection_unique ON hcc_rule_rejection_state(patient_id, rule_id, model_type);

-- Synthetic patient data tables for H2 testing

-- Patient demographics
CREATE TABLE hcc_patient (
    patient_id VARCHAR(100) PRIMARY KEY,
    age INT,
    sex VARCHAR(10),
    enrollment_type VARCHAR(10)
);

-- Lab results
CREATE TABLE hcc_lab_result (
    id BIGSERIAL PRIMARY KEY,
    patient_id VARCHAR(100) NOT NULL,
    concept_alias VARCHAR(255) NOT NULL,
    result_date DATE NOT NULL,
    qualitative_result VARCHAR(50),
    quantitative_result DECIMAL(10,2),
    CONSTRAINT fk_lab_patient FOREIGN KEY (patient_id) REFERENCES hcc_patient(patient_id) ON DELETE CASCADE
);

CREATE INDEX idx_lab_patient ON hcc_lab_result(patient_id);
CREATE INDEX idx_lab_concept ON hcc_lab_result(concept_alias);

-- Medication orders
CREATE TABLE hcc_medication_order (
    id BIGSERIAL PRIMARY KEY,
    patient_id VARCHAR(100) NOT NULL,
    concept_alias VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    combination_type VARCHAR(20),
    CONSTRAINT fk_med_patient FOREIGN KEY (patient_id) REFERENCES hcc_patient(patient_id) ON DELETE CASCADE
);

CREATE INDEX idx_med_patient ON hcc_medication_order(patient_id);
CREATE INDEX idx_med_concept ON hcc_medication_order(concept_alias);

-- Diagnosis/condition records
CREATE TABLE hcc_diagnosis (
    id BIGSERIAL PRIMARY KEY,
    patient_id VARCHAR(100) NOT NULL,
    icd_code VARCHAR(20) NOT NULL,
    hcc_category VARCHAR(50),
    model_type VARCHAR(10) NOT NULL,
    suppression_status VARCHAR(50),
    CONSTRAINT fk_diag_patient FOREIGN KEY (patient_id) REFERENCES hcc_patient(patient_id) ON DELETE CASCADE
);

CREATE INDEX idx_diag_patient ON hcc_diagnosis(patient_id);
CREATE INDEX idx_diag_hcc ON hcc_diagnosis(hcc_category);
CREATE INDEX idx_diag_model ON hcc_diagnosis(model_type);
